In [1]:
# NumPyをインポート
import numpy as np

# 9行x9列の2次元配列を作成
# (すべての要素を0で初期化して作成)
# (4) ゼロで埋めるのは zeros
d = np.zeros((9, 9))

# dは要素がfloat64型の配列であるため
# 整数のint8型の配列に変換
# (5) 型を変換するのは astype
d = d.astype(np.int8)

# 二重ループで九九の表を作成
for i in range(9):
    for j in range(9):
        # インデックス(i, j)は0から始まるので、+1して掛け算する
        # (例: i=0, j=0 のとき 1*1=1 を入れる)
        d[i, j] = (i + 1) * (j + 1)

print(d)

[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]
