In [1]:
# NumPyをインポート
import numpy as np

# 1から9までの連続した整数値の1次元配列aを作成
# (1) [ ] のリストをNumPy配列に変換するのは np.array
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# 1から9までの連続した整数値の1次元配列bを作成
# (aとは別の方法で作成)
# (2) 範囲を指定して連番を作るのは np.arange (終了値10は含まない)
b = np.arange(1, 10)

# bを9行x1列の2次元配列に変換
# (3) 形を変えるのは reshape
b = b.reshape(9, 1)

# 以下のような行列のかけ算を行うことで
# 9行x9列の2次元配列（九九の表）が作成される
# (ブロードキャストという機能で、自動的に縦横に拡張されて計算されます)
c = a * b

# cを表示
print(c)

[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]
